Pin connection_pool gem version
Apps that depend upon this govuk_sidekiq are getting

```
ArgumentError: unknown keyword: :name
```

This seems to be related to https://github.com/mperham/connection_pool/issues/210

We will pin the version until a backport to v7 is available, or an upgrade to v8 is complete: https://gov-uk.atlassian.net/browse/PP-7021?atlOrigin=eyJpIjoiMjAyMWMwMTQxYzlhNGQ5YTk5NDVkNTJlYjQ4MGJhN2EiLCJwIjoiaiJ